config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, controllers: { registrations: 'registrations' }

  get 'line_items/create'

  get 'line_items/update'

  get 'line_items/destroy'

  get 'carts/show'

  resources :line_items
  resource :cart, only: [:show]
  resources :charges

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'
  get '/contact' => 'products#contact'
  get '/about'   => 'products#about'

  get '/category' => 'products#index'

  post '/admin/contact/set_text' => 'products#set_contact_text'
  post '/admin/about/set_text'   => 'products#set_about_text'

  # match "/admin/contact" => 'admin_users#ddd', via: :post
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :category
  has_many :line_items
  has_many :orders, through: :line_items
  has_attached_file :image, url: '/:basename.:extension'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.search(search)
    where('name LIKE ?', "%#{search}%") if search
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @line_item = current_order.line_items.new

    @categories = Category.pluck(:name, :id)

    if params[:search]

      if params[:search_param]

        case params[:search_param]
        when 'all'
          @products = Product.all.limit(6).search(params[:search]).order('created_at DESC')
          @cat_value = nil
        when 'Processors'
          @products = Product.where('category_id = ?', 1).search(params[:search]).order('created_at DESC')
          @cat_value = 1
        when 'GraphicsCards'
          @products = Product.where('category_id = ?', 2).search(params[:search]).order('created_at DESC')
          @cat_value = 2
        when 'Computers'
          @products = Product.where('category_id = ?', 3).search(params[:search]).order('created_at DESC')
          @cat_value = 3
        end

      else

        @products = Product.search(params[:search]).order('created_at DESC')

    end
    end

    case params[:category]
    when 'Show All'
      @products = Product.all.limit(6)
      @cat_value = nil
    when 'Processors'
      @products = Product.where('category_id = ?', 1)
      @cat_value = 1
    when 'GraphicsCards'
      @products = Product.where('category_id = ?', 2)
      @cat_value = 2
    when 'Computers'
      @products = Product.where('category_id = ?', 3)
      @cat_value = 3
    end

    if params[:page].to_i > 1

      @display = (params[:page].to_i - 1) * 6

      @products = Product.limit(6).offset(@display)
    end

    if @products.count > 6
      @products   = Product.all.limit(6)
      @pagintated = Product.all.count / 6.0
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @line_item = current_order.line_items.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def contact
    # $text = session[:my_key1]
  end

  def about
    # $text = session[:my_key1]
  end

  def set_contact_text
    # session[:my_key1] = 'my value'
    # redirect_to "/"

    $contact_text = params[:my_field]
  end

  def set_about_text
    # session[:my_key1] = 'my value'
    # redirect_to "/"

    $about_text = params[:my_field]
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :description, :price, :stock_quantity, :image, :created_at, :updated_at)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :stock_quantity %>
    <%= f.number_field :stock_quantity %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_area :image %>
  </div>

  <div class="field">
    <%= f.label :created_at %>
    <%= f.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= f.label :updated_at %>
    <%= f.datetime_select :updated_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_menu.html.erb
<div class="navbar navbar-inverse navbar-static-top" role="navigation">

	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" rel="home" href="/" title="Aahan Krish's Blog - Homepage">Electronics R Us</a>
	</div>

	<div class="collapse navbar-collapse navbar-ex1-collapse">

		<ul class="nav navbar-nav">
			<li><a href="/topic/notes/">/link 1</a></li>
			<li><a href="/contact">/contact</a></li>
			<li><a href="/about">/about</a></li>
			<%if signed_in?%>
				<%if current_user != nil%>
					<li><%=link_to current_user.email, edit_user_registration_path%></li>
				<% end %>
				<li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
			<%else%>
				<li><%=link_to "Register", new_user_registration_path%></li>
				<li><%=link_to "Login", new_user_session_path%></li>
			<%end%>

		</ul>

		<h1 class="cart-text pull-right"><%= render 'layouts/cart_text' %></h1>

		<div class="col-sm-3 col-md-3 pull-right">
  		<form class="navbar-form" role="search">
  		<div class="input-group nav-search">
        <%= text_field_tag :search, params[:search], placeholder: "Search Posts", :class => "form-control"%>
  			<div class="input-group-btn">
					<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
							<span id="search_concept">Filter by</span> <span class="caret"></span>
					</button>
					<ul class="dropdown-menu" role="menu">
						<li><a href="#Processors">Processors</a></li>
						<li><a href="#GraphicsCards">Graphics Cards</a></li>
						<li><a href="#Computers">Computers ></a></li>
						<li class="divider"></li>
						<li><a href="#all">All</a></li>
					</ul>
					<input type="hidden" name="search_param" value="all" id="search_param">
  				<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
  			</div>
  		</div>
  		</form>

		</div>

	</div>
</div>

<script>

  $(document).ready(function () {
      $('.dropdown-toggle').dropdown();


			$('.dropdown-menu').find('a').click(function(e) {
				e.preventDefault();
				document.getElementById("search_concept").innerHTML=$(this).text();
				var param = $(this).attr("href").replace("#","");
				var concept = $(this).text();
				$('.search-panel span#search_concept').text(concept);
				$('.input-group #search_param').val(param);
		});


  });

</script>

app/views/products/_product_row.html.erb
  <a href="<%= product_path(product) %>">
       <img src="<%=product.image %>" alt="image" class="thumbnail img-responsive">
  </a>
  <div class="col-md-12">
    <h3><%=product.name %></h3>
    <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>

  </div>

app/views/products/about.html.erb
<%= render 'menu' %>

<div class="centered"
	<div class="row">

		<% if $about_text != nil %>
			<p><%= $about_text.inspect.gsub( /\A"/m, "" ).gsub( /"\Z/m, "" ) %></p>
		<% else %>
		  <p>This is some sample text for the about page</p>
		<% end %>

	</div>
</div>

app/views/products/contact.html.erb
<%= render 'menu' %>

<div class="centered"
	<div class="row">

		<% if $contact_text != nil %>
			<p><%= $contact_text.inspect.gsub( /\A"/m, "" ).gsub( /"\Z/m, "" ) %></p>
		<% else %>
		  <p>This is some sample text for the contact page</p>
		<% end %>

	</div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= render 'menu' %>

<div class="centered">

	<div class="row">
		<div class="index-dropdown">
			<% if @cat_value != nil  %>
				<%= select("name", "id", @categories, :selected => @cat_value, :include_blank => 'Show All') %>
			<% else %>
				<%= select("name", "id", @categories, :include_blank => 'Show All') %>
			<% end %>
		</div>

	  <% @products.each do |product| %>
		    <div class="col-lg-4 col-sm-6 col-xs-12 custom-border">
					<%= render "product_row", product: product, line_item: @line_item %>
		  	</div>
	    <% end %>

	</div>
	<div class="container">
  <ul class="pagination">

		<% if @pagintated != nil  %>
			<% @count = (@pagintated / 1)%>
			<% (1..@count).each do |i| %>
				<li><a href="<% request.original_url %>/?page=<%= i %>" ><%= i %></a></li>
				<% @i = i%>
			<% end %>
			<% if @pagintated % 1 != 0 && @pagintated != nil %>
			<li><a href="<% request.original_url %>/?page=<%= @i + 1 %>" ><%= @i + 1 %></a></li>
			<% end %>
		<% else %>

		<% end %>

  </ul>
</div>
</div>


<script>
  $("select").change(function(){

		var dropdown = document.getElementById("name_id");
		var selectedText = dropdown.options[dropdown.selectedIndex].text;

		window.location.href = "<% request.original_url %>" + "/?category=" + selectedText;

  });
</script>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= render 'menu' %>


<p id="notice"><%= notice %></p>

<div class="col-lg-4 col-sm-6 col-xs-12 custom-border" style="margin-right: 20px;">
  <img src="<%=@product.image %>" alt="image" class="thumbnail img-responsive">
</div>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Stock quantity:</strong>
  <%= @product.stock_quantity %>
</p>


  <%= form_tag("/line_items", remote: true,  method: "post") do %>
    <div class="input-group">
      <%= hidden_field_tag :tab , "line_item" %>
      <div style="display: inline-block;">
        <%= number_field(:line_item, :quantity, in: 1.0..20.0, value: 1, min: 0, step: 1) %>
      </div>
      <div style="display: inline-block;">
        <%= hidden_field_tag "line_item[product_id]", @product.id %>
        <%= submit_tag("Add to Cart") %>
      </div>
    </div>
  <% end %>