config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, controllers: { registrations: 'registrations' }

  get 'line_items/create'

  get 'line_items/update'

  get 'line_items/destroy'

  get 'carts/show'

  resources :line_items
  resource :cart, only: [:show]
  resources :charges

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'
  get '/contact' => 'products#contact'
  get '/about'   => 'products#about'

  get '/category' => 'products#index'

  post '/admin/contact/set_text' => 'products#set_contact_text'
  post '/admin/about/set_text'   => 'products#set_about_text'

  # match "/admin/contact" => 'admin_users#ddd', via: :post
end

app/views/layouts/_cart_text.html.erb
<% @cart_quantity = 0 %>
<% current_order.line_items.each do |line_item| %>
  <% @cart_quantity += line_item.quantity %>
<% end %>
<%= link_to  @cart_quantity.to_s + " Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link cart-text-white", style: "color: white;" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProject</title>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <% if request.ssl? %>
      <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
      <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
    <% else %>
      <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
      <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
    <% end %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>